
title = "gitleaks config"

[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[allowlist]
regexes = [
   '''(?i)(client[_-]?ID|AppInsightKey|InstrumentationKey)["']?\s*[:=]\s*["']?[a-zA-Z0-9]{8}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{12}'''
]

stopwords= [
    "devops_region",
    "central_logs_region"
]

paths = [
  '''examples''',
]